[package]
name = "sed_bad"
version = "0.1.0"
authors = ["saruman9 <rum.274.4@gmail.com>"]

[dependencies]
chrono = "0.2"
md5 = "0.2"
gpgme = "0.4"

[dependencies.rusqlite]
version = "0.7"
features = ["chrono"]

[dependencies.gtk]
version = "0.1"
features = ["v3_16"]
